//! Support traits and collection families for code generated by crepe.
//!
//! Implement [`CrepeCollections`] to select the relation set and relation map
//! types used by a generated `Crepe` runtime. The included default collection
//! family is simple and deterministic; applications can provide their own
//! storage by implementing the traits in this crate.

#![forbid(unsafe_code)]
#![deny(missing_docs)]

use std::collections::{BTreeMap, BTreeSet};

mod sealed {
    pub trait RelationSetSealed<T> {}

    impl<C, T> RelationSetSealed<T> for C
    where
        C: super::CrepeCollections,
        C::Set<T>: super::RelationSet<T>,
    {
    }

    pub trait RelationMapSealed<K, V> {}

    impl<C, K, V> RelationMapSealed<K, V> for C
    where
        C: super::CrepeCollections,
        C::Collection<V>: super::RelationCollection<V>,
        C::Map<K, V>: super::RelationMap<K, V, Values = C::Collection<V>>,
    {
    }
}

/// A collection of relation values stored under one relation-map key.
pub trait RelationCollection<T>: Default {
    /// Iterator returned by [`RelationCollection::iter`].
    type Iter<'a>: Iterator<Item = &'a T>
    where
        Self: 'a,
        T: 'a;

    /// Push a relation value into this collection.
    fn push(&mut self, value: T);

    /// Iterate over values in this collection.
    fn iter(&self) -> Self::Iter<'_>;
}

impl<T> RelationCollection<T> for Vec<T> {
    type Iter<'a>
        = std::slice::Iter<'a, T>
    where
        Self: 'a,
        T: 'a;

    fn push(&mut self, value: T) {
        Vec::push(self, value);
    }

    fn iter(&self) -> Self::Iter<'_> {
        self.as_slice().iter()
    }
}

/// A set of relation values used for base, delta, and output relations.
pub trait RelationSet<T>: Default {
    /// Iterator returned by [`RelationSet::iter`].
    type Iter<'a>: Iterator<Item = &'a T>
    where
        Self: 'a,
        T: 'a;

    /// Insert a relation value, returning whether it was not already present.
    fn insert(&mut self, value: T) -> bool;

    /// Return whether the relation value is already present.
    fn contains(&self, value: &T) -> bool;

    /// Return whether this relation set contains no values.
    fn is_empty(&self) -> bool;

    /// Iterate over values in this relation set.
    fn iter(&self) -> Self::Iter<'_>;

    /// Extend this set with values from an iterator.
    fn extend<I>(&mut self, iter: I)
    where
        I: IntoIterator<Item = T>,
    {
        for value in iter {
            self.insert(value);
        }
    }

    /// Extend this set with all values from another relation set.
    fn extend_set(&mut self, other: &Self)
    where
        T: Copy,
    {
        self.extend(other.iter().copied());
    }

    /// Insert a relation value only when it is missing from another set.
    fn insert_if_missing(&mut self, existing: &Self, value: T) -> bool {
        if existing.contains(&value) {
            false
        } else {
            self.insert(value)
        }
    }
}

/// A small deterministic relation set backed by a vector.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct VecRelationSet<T>(Vec<T>);

impl<T> Default for VecRelationSet<T> {
    fn default() -> Self {
        Self(Vec::new())
    }
}

impl<T> VecRelationSet<T> {
    /// Return the number of stored relation values.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Return whether this relation set contains no values.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Iterate over stored relation values.
    pub fn iter(&self) -> std::slice::Iter<'_, T> {
        self.0.iter()
    }
}

impl<T: PartialEq> VecRelationSet<T> {
    /// Return whether the relation value is already present.
    pub fn contains(&self, value: &T) -> bool {
        self.0.contains(value)
    }
}

impl<T: PartialEq> RelationSet<T> for VecRelationSet<T> {
    type Iter<'a>
        = std::slice::Iter<'a, T>
    where
        Self: 'a,
        T: 'a;

    fn insert(&mut self, value: T) -> bool {
        if self.0.contains(&value) {
            false
        } else {
            self.0.push(value);
            true
        }
    }

    fn contains(&self, value: &T) -> bool {
        self.0.contains(value)
    }

    fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    fn iter(&self) -> Self::Iter<'_> {
        self.0.iter()
    }
}

impl<T> IntoIterator for VecRelationSet<T> {
    type Item = T;
    type IntoIter = std::vec::IntoIter<T>;

    fn into_iter(self) -> Self::IntoIter {
        self.0.into_iter()
    }
}

impl<'a, T> IntoIterator for &'a VecRelationSet<T> {
    type Item = &'a T;
    type IntoIter = std::slice::Iter<'a, T>;

    fn into_iter(self) -> Self::IntoIter {
        self.0.iter()
    }
}

impl<T: PartialEq> Extend<T> for VecRelationSet<T> {
    fn extend<I>(&mut self, iter: I)
    where
        I: IntoIterator<Item = T>,
    {
        RelationSet::extend(self, iter);
    }
}

/// A map from bound relation-field keys to relation values matching that key.
pub trait RelationMap<K, V>: Default {
    /// Collection stored for each key.
    type Values: RelationCollection<V>;

    /// Get relation values stored for a key.
    fn get(&self, key: &K) -> Option<&Self::Values>;

    /// Get the mutable collection for a key, creating it when absent.
    fn values_mut_or_default(&mut self, key: K) -> &mut Self::Values;

    /// Return whether the map contains a key.
    fn contains_key(&self, key: &K) -> bool {
        self.get(key).is_some()
    }

    /// Return whether the map does not contain a key.
    fn is_key_absent(&self, key: &K) -> bool {
        !self.contains_key(key)
    }

    /// Push one relation value under a key.
    fn push(&mut self, key: K, value: V) {
        self.values_mut_or_default(key).push(value);
    }

    /// Push every value from a relation set, deriving each map key with a closure.
    fn extend_from_set<S, F>(&mut self, set: &S, mut key: F)
    where
        S: RelationSet<V>,
        V: Copy,
        F: FnMut(&V) -> K,
    {
        for value in set.iter() {
            self.push(key(value), *value);
        }
    }

    /// Iterate over values stored for a key.
    fn iter_key(&self, key: &K) -> Option<<Self::Values as RelationCollection<V>>::Iter<'_>> {
        self.get(key).map(RelationCollection::iter)
    }
}

/// A small deterministic relation map backed by a vector.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct VecRelationMap<K, V>(Vec<(K, Vec<V>)>);

impl<K, V> Default for VecRelationMap<K, V> {
    fn default() -> Self {
        Self(Vec::new())
    }
}

impl<K: PartialEq, V> RelationMap<K, V> for VecRelationMap<K, V> {
    type Values = Vec<V>;

    fn get(&self, key: &K) -> Option<&Self::Values> {
        self.0
            .iter()
            .find(|(stored, _)| stored == key)
            .map(|(_, values)| values)
    }

    fn values_mut_or_default(&mut self, key: K) -> &mut Self::Values {
        if let Some(index) = self.0.iter().position(|(stored, _)| stored == &key) {
            &mut self.0[index].1
        } else {
            self.0.push((key, Vec::new()));
            &mut self.0.last_mut().expect("entry was just inserted").1
        }
    }
}

impl<T> RelationSet<T> for BTreeSet<T>
where
    T: Ord,
{
    type Iter<'a>
        = std::collections::btree_set::Iter<'a, T>
    where
        Self: 'a,
        T: 'a;

    fn insert(&mut self, value: T) -> bool {
        BTreeSet::insert(self, value)
    }

    fn contains(&self, value: &T) -> bool {
        BTreeSet::contains(self, value)
    }

    fn is_empty(&self) -> bool {
        BTreeSet::is_empty(self)
    }

    fn iter(&self) -> Self::Iter<'_> {
        BTreeSet::iter(self)
    }
}

impl<K, V> RelationMap<K, V> for BTreeMap<K, Vec<V>>
where
    K: Ord,
{
    type Values = Vec<V>;

    fn get(&self, key: &K) -> Option<&Self::Values> {
        BTreeMap::get(self, key)
    }

    fn values_mut_or_default(&mut self, key: K) -> &mut Self::Values {
        self.entry(key).or_default()
    }
}

/// A family of collection types used by a generated `Crepe` runtime.
///
/// The associated types are intentionally unconstrained here. Generated code
/// adds the exact [`RelationSet`], [`RelationMap`], and [`RelationCollection`]
/// bounds it needs for the concrete relation and key types in a Datalog program.
pub trait CrepeCollections {
    /// Relation set used for base, delta, and output relations.
    type Set<T>;

    /// Relation map used for generated indices.
    type Map<K, V>;

    /// Per-key collection used by generated indices.
    type Collection<T>;
}

/// Marker trait for collection families whose set supports a relation type.
///
/// This is implemented automatically when the selected [`CrepeCollections::Set`]
/// implements [`RelationSet`] for `T`.
pub trait SupportsRelationSet<T>: CrepeCollections + sealed::RelationSetSealed<T> {
    /// Set type known to implement [`RelationSet`] for `T`.
    type Set: RelationSet<T>;
}

impl<C, T> SupportsRelationSet<T> for C
where
    C: CrepeCollections,
    C::Set<T>: RelationSet<T>,
{
    type Set = C::Set<T>;
}

/// Relation set selected by a collection family, with its support bound proven.
pub type RelationSetOf<C, T> = <C as SupportsRelationSet<T>>::Set;

/// Marker trait for collection families whose map supports an index key/value.
///
/// This is implemented automatically when the selected map and per-key
/// collection satisfy the relation-map contract for `K` and `V`.
pub trait SupportsRelationMap<K, V>: CrepeCollections + sealed::RelationMapSealed<K, V> {
    /// Per-key collection type known to implement [`RelationCollection`].
    type Collection: RelationCollection<V>;

    /// Map type known to implement [`RelationMap`] for `K` and `V`.
    type Map: RelationMap<K, V, Values = <Self as SupportsRelationMap<K, V>>::Collection>;
}

impl<C, K, V> SupportsRelationMap<K, V> for C
where
    C: CrepeCollections,
    C::Collection<V>: RelationCollection<V>,
    C::Map<K, V>: RelationMap<K, V, Values = C::Collection<V>>,
{
    type Collection = C::Collection<V>;
    type Map = C::Map<K, V>;
}

/// Relation map selected by a collection family, with its support bound proven.
pub type RelationMapOf<C, K, V> = <C as SupportsRelationMap<K, V>>::Map;

/// Default crepe collection family.
pub struct DefaultCrepeCollections;

impl CrepeCollections for DefaultCrepeCollections {
    type Set<T> = VecRelationSet<T>;
    type Map<K, V> = VecRelationMap<K, V>;
    type Collection<T> = Vec<T>;
}

/// Ordered crepe collection family.
pub struct OrderedCrepeCollections;

impl CrepeCollections for OrderedCrepeCollections {
    type Set<T> = BTreeSet<T>;
    type Map<K, V> = BTreeMap<K, Vec<V>>;
    type Collection<T> = Vec<T>;
}
