//! Support traits and collection families for code generated by crepe.
//!
//! Implement [`CrepeCollections`] to select the relation set, relation map, and
//! per-key collection types used by a generated `Crepe` runtime. Built-in
//! collection families are selected with crate features; applications can still
//! provide their own storage by implementing the traits in this crate.

#![cfg_attr(not(feature = "std"), no_std)]
#![forbid(unsafe_code)]
#![deny(missing_docs)]

#[cfg(feature = "alloc")]
extern crate alloc;

/// Re-export of the `crepe!` procedural macro.
pub use crepe_macro::crepe;

#[cfg(not(any(
    feature = "std",
    feature = "fnv",
    feature = "hashbrown",
    feature = "heapless"
)))]
compile_error!(
    "enable at least one crepe collection backend feature: std, fnv, hashbrown, or heapless"
);

/// A collection of relation values stored under one relation-map key.
pub trait RelationCollection<T>: Default {
    /// Iterator returned by [`RelationCollection::iter`].
    type Iter<'a>: Iterator<Item = &'a T>
    where
        Self: 'a,
        T: 'a;

    /// Push a relation value into this collection.
    fn push(&mut self, value: T);

    /// Iterate over values in this collection.
    fn iter(&self) -> Self::Iter<'_>;
}

/// A set of relation values used for base, delta, and output relations.
pub trait RelationSet<T>: Default + Extend<T> {
    /// Iterator returned by [`RelationSet::iter`].
    type Iter<'a>: Iterator<Item = &'a T>
    where
        Self: 'a,
        T: 'a;

    /// Insert a relation value, returning whether it was not already present.
    fn insert(&mut self, value: T) -> bool;

    /// Return whether the relation value is already present.
    fn contains(&self, value: &T) -> bool;

    /// Return whether this relation set contains no values.
    fn is_empty(&self) -> bool;

    /// Iterate over values in this relation set.
    fn iter(&self) -> Self::Iter<'_>;

    /// Insert a relation value only when it is missing from another set.
    fn insert_if_missing(&mut self, existing: &Self, value: T) -> bool {
        !existing.contains(&value) && self.insert(value)
    }
}

/// A map from bound relation-field keys to relation values matching that key.
pub trait RelationMap<K, V>: Default {
    /// Collection stored for each key.
    type Values: RelationCollection<V>;

    /// Get relation values stored for a key.
    fn get(&self, key: &K) -> Option<&Self::Values>;

    /// Get the mutable collection for a key, creating it when absent.
    fn values_mut_or_default(&mut self, key: K) -> &mut Self::Values;

    /// Return whether the map does not contain a key.
    fn is_key_absent(&self, key: &K) -> bool {
        self.get(key).is_none()
    }

    /// Push one relation value under a key.
    fn push(&mut self, key: K, value: V) {
        self.values_mut_or_default(key).push(value);
    }

    /// Push every value from a relation set, deriving each map key with a closure.
    fn extend_from_set<S, F>(&mut self, set: &S, mut key: F)
    where
        S: RelationSet<V>,
        V: Copy,
        F: FnMut(&V) -> K,
    {
        for value in set.iter() {
            self.push(key(value), *value);
        }
    }

    /// Iterate over values stored for a key.
    fn iter_key(&self, key: &K) -> Option<<Self::Values as RelationCollection<V>>::Iter<'_>> {
        self.get(key).map(RelationCollection::iter)
    }
}

/// A family of collection types used by a generated `Crepe` runtime.
///
/// The `Set` and `Map` associated types are intentionally unconstrained here so
/// the family declaration can name types whose own bounds (e.g. `T: Hash + Eq`
/// for `HashSet`) cannot hold for every `T`. The generated runtime adds the
/// exact [`RelationSet`] and [`RelationMap`] bounds it needs for the concrete
/// relation and key types in a Datalog program.
pub trait CrepeCollections {
    /// Relation set used for base, delta, and output relations.
    type Set<T>;

    /// Relation map used for generated indices.
    type Map<K, V>;

    /// Per-key collection used by generated indices.
    type Collection<T>: RelationCollection<T>;
}

/// Default fixed capacity used by built-in fixed-capacity collection families.
pub const DEFAULT_FIXED_CAPACITY: usize = 32;

#[cfg(feature = "alloc")]
mod impl_alloc;

#[cfg(feature = "std")]
mod impl_std;

#[cfg(feature = "fnv")]
mod impl_fnv;

#[cfg(feature = "hashbrown")]
mod impl_hashbrown;

#[cfg(feature = "heapless")]
mod impl_heapless;

#[cfg(feature = "fnv")]
pub use impl_fnv::FnvCrepeCollections;
#[cfg(feature = "hashbrown")]
pub use impl_hashbrown::HashbrownCrepeCollections;
#[cfg(feature = "heapless")]
pub use impl_heapless::{HeaplessCrepeCollections, HeaplessRelationSet};
#[cfg(feature = "std")]
pub use impl_std::StdCrepeCollections;

/// Default crepe collection family selected by enabled features.
#[cfg(feature = "fnv")]
pub type DefaultCrepeCollections = FnvCrepeCollections;

/// Default crepe collection family selected by enabled features.
#[cfg(all(not(feature = "fnv"), feature = "std"))]
pub type DefaultCrepeCollections = StdCrepeCollections;

/// Default crepe collection family selected by enabled features.
#[cfg(all(not(any(feature = "fnv", feature = "std")), feature = "hashbrown"))]
pub type DefaultCrepeCollections = HashbrownCrepeCollections;

/// Default crepe collection family selected by enabled features.
#[cfg(all(
    not(any(feature = "fnv", feature = "std", feature = "hashbrown")),
    feature = "heapless"
))]
pub type DefaultCrepeCollections = HeaplessCrepeCollections<DEFAULT_FIXED_CAPACITY>;
